name: Generating docs using doxygen

on: push

jobs:
  gen_docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Updating
        run: sudo apt update -y
      
      - name: Installing python3
        run: sudo apt install -y python3 python3-pip
      
      - name: Installing requirements
        run: pip3 install -r requirements.txt

      - name: Formatting all python files
        run: make html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-generating docs"
          git push
      
      - name: Publishing docs on github pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: docs/html

